# Generated by Django 6.0.7 on 2026-07-14 09:15

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisMetadata',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('classification', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('highlighted_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=100)),
                ('raw_text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_metadata', django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model='analytics_engine.analysismetadata', null=True)),
                ('polymorphic_payload', models.JSONField(blank=True, default=dict)),
                ('annotations', django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model='analytics_engine.annotation')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
