"""Add raw_file BinaryField to Document."""

# Generated by Django 6.0.7 on 2026-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    """Store uploaded file bytes for vision-based analysis."""

    dependencies = [
        ('analytics_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='raw_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
